# Generated by Django 3.2 on 2023-11-12 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_alter_userifm_username'),
        ('ifm', '0006_alter_userdefifm_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignLanguageCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picurl', models.TextField(null=True)),
                ('videourl', models.TextField(null=True)),
                ('vocabularie', models.CharField(default='', max_length=50)),
                ('chinese', models.CharField(default='', max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.userifm', to_field='id')),
            ],
        ),
    ]
