# Generated by Django 3.2 on 2023-11-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discuss',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.CharField(max_length=30)),
                ('upload_date', models.DateField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_user', to='reg.userifm', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='DiscussResponse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('response', models.TextField()),
                ('upload_date', models.DateField(default=False)),
                ('dis_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.discuss')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reg.userifm', to_field='id')),
            ],
        ),
    ]
