# Generated by Django 3.2 on 2023-08-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discuss',
            old_name='context',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='discuss',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discussresponse',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
