# Generated by Django 3.2 on 2023-10-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userifm',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
