# Generated by Django 3.2 on 2023-08-11 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0003_alter_teachwordcard_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teach',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
    ]
