# Generated by Django 3.2 on 2023-08-11 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_teach'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teach',
            new_name='TeachType',
        ),
    ]
