# Generated by Django 3.2 on 2023-11-14 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeachWordCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img', models.ImageField(upload_to='studyimage/english')),
                ('upload_date', models.DateField(default='1900-01-01')),
                ('describe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mondai', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test2',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('vocabularie', models.CharField(default='', max_length=50)),
                ('chinese', models.CharField(default='', max_length=255)),
                ('describe', models.TextField(null=True)),
                ('videourl', models.TextField(null=True)),
                ('picurl', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test2Ans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kotae_ichi', models.CharField(max_length=255)),
                ('kotae_ni', models.CharField(max_length=255)),
                ('kotae_san', models.CharField(max_length=255)),
                ('kotae_yon', models.CharField(max_length=255)),
                ('kotae_go', models.CharField(max_length=255)),
                ('cor_rate', models.FloatField(default=100.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.userifm', to_field='id')),
            ],
        ),
        migrations.CreateModel(
            name='Test1Ans',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kotae_ichi', models.CharField(max_length=20)),
                ('kotae_ni', models.CharField(max_length=20)),
                ('kotae_san', models.CharField(max_length=20)),
                ('kotae_yon', models.CharField(max_length=20)),
                ('kotae_go', models.CharField(max_length=20)),
                ('cor_rate', models.FloatField(default=100.0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reg.userifm', to_field='id')),
            ],
        ),
    ]
