# Generated by Django 3.2 on 2023-08-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachwordcard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
