# Generated by Django 3.2 on 2023-11-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_auto_20230825_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test2',
            name='mondai',
        ),
        migrations.AddField(
            model_name='test2',
            name='chinese',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='test2',
            name='describe',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='test2',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='test2',
            name='vocabularie',
            field=models.CharField(default='', max_length=50),
        ),
    ]
