# Generated by Django 3.2 on 2023-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_auto_20231112_0049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test2',
            old_name='url',
            new_name='picurl',
        ),
        migrations.AddField(
            model_name='test2',
            name='videourl',
            field=models.TextField(null=True),
        ),
    ]
