# Generated by Django 3.2 on 2023-11-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0008_auto_20231112_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
