# Generated by Django 3.2 on 2023-11-12 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0009_alter_test2_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2',
            name='chinese',
            field=models.CharField(default='', max_length=255),
        ),
    ]
