# Generated by Django 3.2 on 2023-11-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0010_alter_test2_chinese'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test2ans',
            name='kotae_go',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test2ans',
            name='kotae_ichi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test2ans',
            name='kotae_ni',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test2ans',
            name='kotae_san',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='test2ans',
            name='kotae_yon',
            field=models.CharField(max_length=255),
        ),
    ]
