# Generated by Django 3.2 on 2023-08-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_alter_teachwordcard_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachwordcard',
            name='img',
            field=models.ImageField(upload_to='studyimage/english'),
        ),
    ]
