# Generated by Django 3.2 on 2023-08-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefIfm',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('headimg', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=256)),
                ('user_id', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='UserIfm',
            fields=[
                ('Email', models.EmailField(max_length=100, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=256)),
                ('id', models.IntegerField(default=0)),
                ('Validation', models.BooleanField(default=False)),
                ('Validation_Num', models.IntegerField(default=0)),
                ('Birthday', models.DateField(default='1900-01-01')),
            ],
        ),
    ]
