# Generated by Django 3.2 on 2023-08-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userifm',
            name='id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
