# Generated by Django 3.2 on 2023-08-03 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_alter_userifm_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDefIfm',
        ),
    ]
