# Generated by Django 3.2 on 2023-10-09 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifm', '0005_rename_user_id_ifm_usewordcard_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefifm',
            name='describe',
            field=models.TextField(),
        ),
    ]
