# Generated by Django 3.2 on 2023-08-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdefifm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userdefifm',
            name='score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
