# Generated by Django 3.2 on 2023-08-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifm', '0002_alter_userdefifm_headimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usewordcard',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
