# Generated by Django 3.2 on 2023-08-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlineChatroom',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('context', models.TextField()),
                ('context_img', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onlinechat_user', to='reg.userifm', to_field='id')),
            ],
        ),
    ]
