# Generated by Django 3.2 on 2023-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Billboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='公告', max_length=30)),
                ('content', models.TextField()),
                ('upload_date', models.DateField(default=False)),
            ],
        ),
    ]
