# Generated by Django 3.2 on 2023-08-23 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billboard',
            name='title',
            field=models.CharField(default='公告', max_length=30),
        ),
        migrations.AlterField(
            model_name='billboard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
