# Generated by Django 3.2 on 2023-08-23 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0002_auto_20230823_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billboard',
            old_name='context',
            new_name='content',
        ),
    ]
