# Generated by Django 3.2 on 2023-11-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OlineChatroom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('username', models.CharField(default='我沒有登入', max_length=100)),
                ('message_img', models.CharField(max_length=100)),
            ],
        ),
    ]
