# Generated by Django 3.2 on 2023-10-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinechat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='olinechatroom',
            old_name='context',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='olinechatroom',
            old_name='context_img',
            new_name='message_img',
        ),
        migrations.RemoveField(
            model_name='olinechatroom',
            name='user',
        ),
        migrations.AddField(
            model_name='olinechatroom',
            name='username',
            field=models.CharField(default='我沒有登入', max_length=100),
        ),
        migrations.AlterField(
            model_name='olinechatroom',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
